### ISSUE TITLE
Failed Medical Emergency Contract

### ISSUE THREAD

**Issue by Blu3wolf** [severedsolo/KerbinSpaceStation#54] opened 2015-12-31 09:04 UTC
I just recovered a medical emergency contract to bring Val back from the Mun Space Station. I accepted a second med emerg contract during the first one's operation, the second being to bring Jeb back from the Kerbin Space Station. On recovery of Val, Jebs contract was failed, costing me a fair amount of funds. Im about to fix this with some .sfs editing, but can I provide any useful information from the file first?

**Comment by Blu3wolf** [comment] 2015-12-31 10:31
Interestingly, following the failed contract, Jeb had somehow managed to get down from orbit himself, and was back at the KSC.

**Comment by severedsolo** [comment] 2015-12-31 10:55
Can't see anything obviously wrong in the contract, but I'm on my phone so may have missed something. Think it may be a cc bug but will need more info - can you provide your unedited save so I can poke about in it? Your log may be good too incase of exceptions 

Note to self - as a workaround change uniquenessCheck to CONTRACT_ACTIVE for now to stop duplicates

**Comment by Blu3wolf** [comment] 2016-01-02 01:11
I didnt save the log, and Ive kept playing on from there - will it still be useful?

If so, where would I find it?

[persistent - Contract Pack Error.zip](https://github.com/severedsolo/KerbinSpaceStation/files/76095/persistent.-.Contract.Pack.Error.zip)

**Comment by severedsolo** [comment] 2016-01-02 09:46
The log would have been overwritten if you've started KSP since then - if you haven't then it can be found in KSP_Data\Output_log (or playerlog if you aren't on Windows).

I'm going to have a poke around your save - will let you know.

pinging @jrossignol in case it's CC

**Comment by severedsolo** [comment] 2016-01-02 09:55
Alright I've had a quick poke through your save. As far as I can tell, the contract generated correctly.

This leaves two options;

The first (my favourite culprit) - is that you caught an exception and it did strange things to your contract. It may even be related to jrossignol/ContractConfigurator#410 (or be the same bug)

Second, Somehow CC has got two contracts with the same subtype confused (seems unlikely, but without a log I doubt it's easily diagnosable)

**Comment by severedsolo** [comment] 2016-01-12 18:36
I still can't reproduce this - did you ever manage to?

**Comment by Blu3wolf** [comment] 2016-01-13 01:30
I havent gotten another medical emergency since this, so no. 
Its not for lack of trying, either - Id estimate Ive played about a hundred hours of KSP since then.

**Comment by severedsolo** [comment] 2016-01-13 09:39
Hmm, GROUP_ACTIVE should definitely make it come back. Looking more and more like an exception.

Six of one half a dozen of the other anyway. I've decided to make missions per active contract rather than per vessel in the next update to encourage contract diversity. That should stop it from happening again.

**Comment by severedsolo** [comment] 2016-01-13 09:41
Closing this down as it will be sorted under #55

**Closed as completed by severedsolo** 2016-01-13 09:41 UTC
